on:
  push:
    branches:
      - master

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: create game release
        uses: firebelley/godot-export@v3.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
          relative_project_path: ./godot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: download HTML5
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            version: "latest"
            file: HTML5.zip
            token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: html
            ITCH_GAME: shmup
            ITCH_USER: destroyerpants
            PACKAGE: HTML5.zip
            VERSION: ${{ steps.download-html.outputs.version }}
